[theme]
primaryColor = "#ff6363"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f7f7"
textColor = "#1a1a1a"
font = "sans serif"
base = "light"

[browser]
gatherUsageStats = false

[server]
maxUploadSize = 200

[client]
showErrorDetails = true
